[model]
name = "Timothee"
optimizer = "adam"
loss = "sparse_categorical_crossentropy"

[[model.layers]]
layer_type = "conv2d"
padding = "same"
filters = 32
strides = [3, 3]

[[model.layers]]
layer_type = "relu"

[[model.layers]]
layer_type = "darbn"

[[model.layers]]
layer_type = "flatten"

[[model.output]]
activation = "softmax"
