[model]
name = "Reynolds"
optimizer = "adam"
loss = "sparse_categorical_crossentropy"


[[model.layers]]
layer_type = "conv2d"
padding = "same"
filters = 32
kernel_size = [3, 3]

[[model.layers]]
layer_type = "relu"

[[model.layers]]
layer_type = "batchnorm"

[[model.layers]]
layer_type = "flatten"

[model.output]
activation = "softmax"


[[model.callbacks]]
callback_type = "early_stopping"
monitor = "val_loss"
min_delta = 1e-2
patience = 5

[hyperparams]
validation_split = 0.2
batch_size = 32
epochs = 10
