[model]
name = "Waltz"
optimizer = "adam"
loss = "sparse_categorical_crossentropy"


[dataset.augmenting]
pad_to_percent = 1.0
replace_with_noise = 0.5


[[model.layers]]
layer_type = "conv2d"
padding = "same"
filters = 32
kernel_size = [3, 3]

[[model.layers]]
layer_type = "relu"

[[model.layers]]
layer_type = "darbn"

[[model.layers]]
layer_type = "flatten"

[model.output]
activation = "softmax"


[hyperparams]
validation_split = 0.2
batch_size = 32
epochs = 10
