[model]
name = "Timothee"
optimizer = "adam"
loss = "sparse_categorical_crossentropy"


[[model.layers]]
layer_type = "conv2d"
padding = "same"
filters = 32
strides = [3, 3]

[[model.layers]]
layer_type = "relu"

[[model.layers]]
layer_type = "darbn"

[[model.layers]]
layer_type = "flatten"

[model.output]
activation = "softmax"


[[model.callbacks]]
callback_type = "early_stopping"
monitor = "val_loss"
min_delta = "1e-2"
patience = "5"


[dataset.augmenting]
# Pad the samples to equal X% of the size of the biggest class.
pad_to_percent = 1.0
# Replace X% of the padding with noise.
replace_with_noise = 0.5

[hyperparams]
validation_split = 0.2
batch_size = 32
epochs = 2
